product/urls.py
from django.urls import path

from . import views


app_name = 'product'

urlpatterns = [
    path('', views.products, name='products'),
    path('woman', views.woman, name='woman'),
    path('products/woman/', views.woman, name='woman'),
    path('products/woman/', views.man, name='man'),

    path('man', views.man, name='man'),    
    path('<int:pk>/', views.details, name='details'),
    path('search_results/', views.search_results, name='search_results'),  # Use search_results view


]

shopp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import index
from product.views import woman
from product.views import man


urlpatterns = [
    path('', index,name='index'),
    path('admin/', admin.site.urls),
    path('products/', include('product.urls'), name='products'),
    path('products/woman/', woman, name='woman'),
    path('products/man/', man, name='man'),







]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from product.models import Category, Product


# Create your views here.


def index(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    return render(request,'core/index.html',{
        'products' : products,
        'categories' : categories
    })

core/templates/core/base.html
{% load static %}

<!doctype html>
<html>
    <head>

        <link rel="icon" href="{% static 'core/favicon.ico' %}" type="image/x-icon">
        <link rel="shortcut icon" href="{% static 'core/favicon.ico' %}" type="image/x-icon">

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">


        <title>{% block title %}{% endblock %} | Shopping </title>
        <!-- Bootstrap CSS -->
      
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'product/css/style.css' %}">


    </head>
<body>
    
 
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Ninth navbar example">
        <div class="container-xl">
        
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07XL" aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">
                </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample07XL">
                <a class="navbar-brand" href="/">
                    <img class="logo" src="{% static 'core/images/logo.png' %}" alt="Logo">
                </a>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/" ">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'product:woman'%}">Woman</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'product:man'%}" >Man</a>
                    </li>
                    
                </ul>

          
               
                <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'product:search_results' %}">
                    <input class="form-control" type="search" name="q" placeholder="Search" aria-label="Search">
                    <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
                  
                </form>


            </div>
        </div>
    </nav>

        <div class="px-6 py-6">
            {% block content %}

            <div class="container mt-4">
                <div class="row row-cols-1 row-cols-md-2 g-4">
                    {% for product in products %}
                        <div class="col">
                            <div class="card">
                                <a href="{% url 'product:details' product.id %}">
                                    <div id="carousel{{ product.id }}" class="carousel slide" data-ride="carousel">
                                        <div class="carousel-inner">
                                            {% for image in product.images.all %}
                                                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                                    <img src="{{ image.image.url }}" class="d-block w-100" alt="Product Image">
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <a class="carousel-control-prev" href="#carousel{{ product.id }}" role="button" data-slide="prev">
                                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                        <a class="carousel-control-next" href="#carousel{{ product.id }}" role="button" data-slide="next">
                                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        <h2 class="card-title">{{ product.name }}</h2>
                                        <p class="card-text">Price: {{ product.price }}</p>
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

            {% endblock %}
        </div>


        <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 mt-5  px-3">
            <div class="col mb-3">
              <a href="/" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none">
                <svg class="bi me-2" width="40" height="32">
                    <img class="logo" src="{% static 'core/images/logo.png' %}" alt="Logo">
                </a>
              <p class="text-body-secondary  ml-5">© 2023</p>
            </div>
        
            <div class="col mb-3">
        
            </div>
        
            <div class="col mb-3">
              <h5>Section</h5>
              <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
              </ul>
            </div>
        
            <div class="col mb-3">
              <h5>Section</h5>
              <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
              </ul>
            </div>
        
            <div class="col mb-3">
              <h5>Section</h5>
              <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
              </ul>
            </div>
          </footer>


     <!-- Bootstrap JS dependencies -->
     <!-- Bootstrap JS dependencies -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-Uo5eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block head %}
    {% load static %} 
    <!-- Add a link to your CSS file -->
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
{% endblock %}

{% block content %}
    <div id="breadcrumbs">
        {% for name, url in breadcrumbs %}
            <a href="{{ url }}">{{ name }}</a>
            {% if not forloop.last %}&rsaquo;{% endif %}
        {% endfor %}
    </div>

    <div class="container mt-4">
        <div class="row row-cols-1 row-cols-md-2 g-4 mb-5">
            {% for product in products %}
                <div class="col">
                    <div class="card">
                        <a href="{% url 'product:details' product.id %}">
                            <div id="carousel{{ product.id }}" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">
                                    {% for image in product.images.all %}
                                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                            <img src="{{ image.image.url }}" class="d-block w-100 carousel-image" alt="Product Image">
                                        </div>
                                    {% endfor %}
                                </div>
                                <a class="carousel-control-prev" href="#carousel{{ product.id }}" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carousel{{ product.id }}" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                            <div class="card-body">
                                <h2 class="card-title">{{ product.name }}</h2>
                                <p class="card-text"> <strong> {{ product.price }} $</strong></p>
                            </div>
                        </a>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:4 and not forloop.last %}
                    </div>
                    <div class="row row-cols-1 row-cols-md-2 g-4  mb-5" >
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}